# Generated by Django 3.2.15 on 2024-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240110_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
