# Generated by Django 3.2.15 on 2024-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_variant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
